# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-16 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_goods_goods_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_name',
            new_name='goods_name',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_number',
            new_name='goods_number',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_price',
            new_name='goods_price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_sales',
        ),
    ]
